### ISSUE TITLE
Migrate the generator items to NeoTTA

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/WorkstationCrafting#2]
Currently, under items/generator, there are a bunch of spawn definitions, item generators, and a world generator. Not to mention all of the deltas and overrides in this module.

All of the first group, and some of the second group should probably be moved into their own world-based module (like TTA was) so that this doesn't conflict with other modules. In the future, I'm intending this module to be a baseline Workstation Crafting module that other modules expand upon. That is, a content-focused module rather than a game or adventure-focused one. But having these generator files can mess with other modules that intend to provide a specific experience.

So moving these plus some of the things left behind in WoodAndStone (like the Journal system and ModifyBlockSystemDestruction) will help this module become easier to extend and have less side-effects. 

This will be a long-term project, as the NeoTTA module will have to be slowly built up bythe pieces from old and new modules.

**Comment by Cervator** [comment]
Think this is roughly complete now that we have a NeoTTA generator over in WoodCrafting?

**Comment by skaldarnar** [comment]
@xrtariq2594 can you give a status update on this issue? Does "roughly complete" qualifies for closing this issue or just reduce it to some outstanding tasks?

**Comment by jdrueckert** [comment]
This seems to be complete by now.
